__author__ = 'asherkhb'
# all_present.py
# Examines coverage files, generates a summary of the species present across all genes.
# Coverage files generated with gene_coverage_matrix.py
# -->Coverage files can be generated from individual partition MSAs (generated by RAxML with indicated command)
#
# User should assign genes that will be compared in 'gene_list'

# User Defined Variables
gene_list = ['18s', '26s', 'atpB', 'ITS', 'matK', 'rbcL', 'trnLtrnF']

# Global Variables
output = 'allpresent_summary.csv'
gene_contents = {}

for gene in gene_list:
    file_name = '%s_present.phy_coverage.csv' % gene
    file_contents = {}
    with open(file_name, 'r') as inpt:
        for line in inpt:
            line_contents = line.split(',')
            species = line_contents[0]
            coverage = line_contents[1].strip('\n')
            file_contents[species] = coverage
    gene_contents[gene] = file_contents

with open(output, 'w') as otpt:
    header = 'Species,' + ','.join(gene_list) + '\n'
    otpt.write(header)
    for spp in gene_contents[gene_list[0]]:
        spps = True
        for i in range(1, len(gene_list)):
            if spp not in gene_contents[gene_list[i]]:
                spps = False
        if spps:
            otpt.write(spp)
            for gene in gene_list:
                otpt.write(',')
                otpt.write(gene_contents[gene][spp])
            otpt.write('\n')